var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                          o     ",
   "                                                       o               xxxxxxx  ",
   "             xxxx                                     xx                     x  ",
   "             xxxx       o                                                    x  ",
   "             xxxx      xxxx                  xx               xx             x  ",
   "             xxxx      !vv!                                                  x  ",
   "             xxxx                  xxxxx                                     x  ",
   "             xxxx                                                            x  ",
   "             xxxx                                                            x  ",
   "             xxxx                                                            x  ",
   "             xxxx                                    xxx                     x  ",
   "  xxx        xxxx                                                 o  o       x  ",
   "  xxx  @     xxxx   o                   xxx                      xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxx                                        x  ",
   "                      x   x         x                                        x  ",
   "                      x!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "                      x???x         x????????????????????????????????????????x  ",
   "                      xxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "      o                                                                                                           ",
   "      xx                                                                                                          ",
   "                                                                     o                                            ",
   "                                                                 xxxxxxxx                                         ",
   "               xx                   xx                                                                            ",
   " xx                                                                                                               ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                               x       xxx                                                        ",
   "                                               x         x                                                        ",
   "                                               x         x                                                        ",
   "         xx                                    x         x                                                        ",
   "                                               xxx       x                                                        ",
   "                                               x         x             x                                          ",
   "                              xxxxxxxxx        x         x!!!!!!!!!!!!!x                                          ",
   "                                               x         xvxxxxxvxxxxxvx                                          ",
   "           o                                   x                                                                  ",
   "     @     x                                   x                                     xx                         ",
   "    xxx!!!!!!!!             !!!!!!!!!!!!!!!!!!!x                                    x  x                          ",
   "    x x??????xv             vx?????????????????x                         o     b   x    x                         ",
   "!!!!x x??????x               x?????????????????x       xxx xxxxx xxxxx xxxxxxxxxxx                                ",
   "????x x??????x               x?????????????????x!!!!!!!!!x                                                        ",
   "????x x??????x               x?????????????????x?????????x                                                        ",
   "????x x??????x      xxx      x?????????????????xxxxxxxxxxx                                                        ",
   "????x x??????x !!!!!!!!!!!!! x????????????????????????????!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "????x x??????x???????????????x???????????????????????????????????????????????????????????????????????????????????x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                    x                                                         ",
   "                                                    x                                                         ",
   "                                                    x                                                         ",
   "      @                                             x  o                                                      ",
   "    xxxxx                                           xxxxxx                                                    ",
   "                                                    x                                                         ",
   "                                                    x                                xxx                      ",
   "       x                                #   x       x                                                         ",
   "       xxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxx       x                                                         ",
   "                                                    x                                                      xxx",
   "                                                    x                                                         ",
   "                                                    x          xxx                                            ",
   "           xx                                       x                                                         ",
   "                                                    x                                                         ",
   "                                                                                                              ",
   "                                          xx                 x #                    x                    # x  ",
   "      xx                xx                                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxx ",
   "                                                                                                              ",
   "                                                                                                              ",
   "               xx                                                                                             ",
   "                                                                                                              ",
   " o                                xx                                                                  o    o  ",
   "xxx                                              xxx                                                 xxxxxxxxx",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "x????????????????????????????????????????????????????????????????????????????????????????????????????????????x",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                          @                                                                                   ",
   "        xx          xx   xx   xx          xx   xx          xx  xxxxxxxxxxxx  xxxxxxxxxx                       ",
   "        xx          xx   xx   xxxx        xx   xxxx        xx  xx            xx        x                      ",
   "        xx          xx   xx   xx  xx      xx   xx  xx      xx  xx            xx        x                      ",
   "        xx    xx    xx   xx   xx    xx    xx   xx    xx    xx  xxxxxxxxxxxx  xxxxxxxxxx                       ",
   "        xx  xx  xx  xx   xx   xx      xx  xx   xx      xx  xx  xx            xx        x                      ",
   "        xxxx      xxxx   xx   xx        xxxx   xx        xxxx  xx            xx         x                     ",
   "        xx          xx   xx   xx          xx   xx          xx  xxxxxxxxxxxx  xx         x                     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
